version: '3'
services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports: 
      - 5432:5432

  training:
    build: .docker/
    ports:
      - 5000:5000
    depends_on:
      - db